resources:
- name: every-morning
  type: time
  source:
    start: 9:30 AM
    stop: 9:45 AM
    days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday

- name: github-code
  type: git
  source:
    uri: https://github.com/vlad-stoian/robbit.git
    branch: master

jobs:
- name: post-retro-items
  plan:
  - get: every-morning
    trigger: true
  - get: github-code
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: alpine
      inputs:
      - name: github-code
      run:
        path: python
        args:
        - "github-code/src/check-it.py"
        - {{retro-id}}
        - {{postfacto-token}}
        - {{slack-token}}
        - {{slack-channel}}

