resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: every-morning
  type: time
  source:
    start: 9:40 AM
    stop: 9:45 AM
    location: Europe/Dublin
    days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday

- name: every-evening
  type: time
  source:
    start: 6:00 PM
    stop: 6:30 PM
    location: Europe/Dublin
    days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday

- name: slack-channel-pcf-rabbitmq
  type: slack-notification
  source:
    url: {{slack-hook-url}}

- name: github-robbit-repo
  type: git
  source:
    uri: git@github.com:vlad-stoian/robbit.git
    branch: master
    private_key: {{github-private-key}}

- name: github-rabbitmq-tile-home-repo
  type: git
  source:
    uri: git@github.com:pivotal-cf/rabbitmq-tile-home.git
    branch: master
    private_key: {{github-private-key}}

- name: github-london-services-locks-repo
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/london-services-locks.git
    branch: master
    private_key: {{github-private-key}}

jobs:
- name: post-retro-items
  plan:
  - get: every-morning
    trigger: true
  - get: github-robbit-repo
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: alpine
      inputs:
      - name: github-robbit-repo
      run:
        path: python
        args:
        - "github-robbit-repo/src/post-retro-items.py"
        - {{postfacto-token}}
        - {{retro-id}}
        - {{slack-token}}
        - {{slack-channel}}

- name: update-channel-topic
  plan:
  - get: every-morning
    trigger: true
  - get: github-robbit-repo
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: alpine
      inputs:
      - name: github-robbit-repo
      run:
        path: python
        args:
        - "github-robbit-repo/src/update-channel-topic.py"
        - {{slack-token}}
        - {{slack-channel}}

- name: clear-channel-topic
  plan:
  - get: every-evening
    trigger: true
  - get: github-robbit-repo
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: alpine
      inputs:
      - name: github-robbit-repo
      run:
        path: python
        args:
        - "github-robbit-repo/src/clear-channel-topic.py"
        - {{slack-token}}
        - {{slack-channel}}

- name: list-claimed-opsman-envs
  plan:
  - get: github-rabbitmq-tile-home-repo
  - get: github-london-services-locks-repo
  - task: annoy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: concourse/git-resource
          tag: latest
      inputs:
      - name: github-rabbitmq-tile-home-repo
      - name: github-london-services-locks-repo
      outputs:
      - name: slack-channel-pcf-rabbitmq
      params:
        LONDON_SERVICE_LOCKS: github-london-services-locks-repo
      run:
        path: sh
        args:
        - -exc
        - |
          mkdir -p ~/.ssh/
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          ls github-rabbitmq-tile-home-repo/bin/list-envs
          ./github-rabbitmq-tile-home-repo/bin/list-envs claimed > slack-channel-pcf-rabbitmq/message

          # echo "message in a file" > slack-channel-pcf-rabbitmq/message

  - put: slack-channel-pcf-rabbitmq
    params:
      text_file: slack-channel-pcf-rabbitmq/message
      username: 'robbit'
      icon_emoji: ':ghost:'

